PRJINCS:=
PRJSRCS:=../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_0.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_1.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_10.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_11.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_12.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_13.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_14.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_15.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_16.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_17.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_18.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_19.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_2.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_20.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_21.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_22.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_23.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_24.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_25.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_26.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_27.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_28.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_29.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_3.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_4.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_5.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_6.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_7.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_8.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/sub_9.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_experimental.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_array.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_mruby_ref.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_value.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/mruby_script_engine.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/sprite_experimental.cpp
-include ../../../libraries/cor_cocos2dx_mruby_interface/proj.common/cor_cocos2dx_mruby_interface_local_conf.mk
