PRJINCS:=
PRJSRCS:=../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_0.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_1.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_10.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_11.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_2.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_3.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_4.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_5.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_6.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_7.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_8.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind/cor_cocos2dx_mruby_sub_9.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos2dx_experimental.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_array.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_mruby_ref.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_value.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/mruby_script_engine.cpp\
    ../../cor_cocos2dx_mruby_interface/sources/sprite_experimental.cpp
-include ../../../libraries/cor_cocos2dx_mruby_interface/proj.common/cor_cocos2dx_mruby_interface_local_conf.mk
