PRJINCS:=
PRJSRCS:=../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_0.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_1.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_10.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_11.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_12.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_13.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_14.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_15.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_16.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_17.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_18.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_19.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_2.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_20.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_21.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_22.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_23.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_24.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_25.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_26.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_27.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_28.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_29.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_3.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_4.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_5.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_6.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_7.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_8.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_9.cpp\
    ../../cor_mruby_interface/sources/basic_bind.cpp\
    ../../cor_mruby_interface/sources/mrubybind.cpp\
    ../../cor_mruby_interface/sources/mruby_array.cpp\
    ../../cor_mruby_interface/sources/mruby_experimental.cpp\
    ../../cor_mruby_interface/sources/mruby_ref_container.cpp\
    ../../cor_mruby_interface/sources/mruby_state.cpp
-include ../../../libraries/cor_mruby_interface/proj.common/cor_mruby_interface_local_conf.mk
