PRJSRCS=../../cor_mruby_interface/sources/basic_bind/sub_0.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_1.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_10.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_11.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_12.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_13.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_14.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_15.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_16.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_17.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_18.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_19.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_2.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_20.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_21.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_22.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_23.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_24.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_25.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_26.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_27.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_28.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_29.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_3.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_4.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_5.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_6.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_7.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_8.cpp\
    ../../cor_mruby_interface/sources/basic_bind/sub_9.cpp\
    ../../cor_mruby_interface/sources/basic_bind.cpp\
    ../../cor_mruby_interface/sources/mrubybind.cpp\
    ../../cor_mruby_interface/sources/mruby_array.cpp\
    ../../cor_mruby_interface/sources/mruby_experimental.cpp\
    ../../cor_mruby_interface/sources/mruby_ref_container.cpp\
    ../../cor_mruby_interface/sources/mruby_state.cpp
