PRJINCS:=
PRJSRCS:=../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_0.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_1.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_10.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_11.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_2.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_3.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_4.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_5.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_6.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_7.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_8.cpp\
    ../../cor_mruby_interface/sources/basic_bind/cor_mruby_sub_9.cpp\
    ../../cor_mruby_interface/sources/basic_bind.cpp\
    ../../cor_mruby_interface/sources/mrubybind.cpp\
    ../../cor_mruby_interface/sources/mruby_array.cpp\
    ../../cor_mruby_interface/sources/mruby_experimental.cpp\
    ../../cor_mruby_interface/sources/mruby_ref_container.cpp\
    ../../cor_mruby_interface/sources/mruby_state.cpp
-include ../../../libraries/cor_mruby_interface/proj.common/cor_mruby_interface_local_conf.mk
