#include "cor_mruby_interface/sources/basic_bind.h"
#include "cor_mruby_interface/sources/mruby_array.h"
#include "cor_mruby_interface/sources/mruby_array_tmpl.h"
#include "cor_mruby_interface/sources/mruby_experimental.h"
#include "cor_mruby_interface/sources/mruby_ref_container.h"
#include "cor_mruby_interface/sources/mruby_state.h"
#include "cor_cocos2dx_converter/sources/cocos2dx_experimental.h"
#include "cor_cocos2dx_converter/sources/collision_2d_node.h"
#include "cor_cocos2dx_converter/sources/easy_http_client.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_cost_grid_space.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_cost_grid_space_e.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_effect.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_group.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_sensor.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_system.h"
#include "cor_cocos2dx_converter/sources/step_size_scene.h"
#include "cor_cocos2dx_converter/sources/textured_triangle_node.h"
#include "cor_cocos2dx_converter/sources/type_converter.h"
#include "cor_cocos2dx_converter/sources/type_converter_tmpl.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_experimental.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_array.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_mruby_ref.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_value.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.h"
#include "cor_cocos2dx_mruby_interface/sources/mruby_script_engine.h"
#include "cor_cocos2dx_mruby_interface/sources/sprite_experimental.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/cocos2d.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/ui/UIEditBox/UIEditBox.h"
#include "../projects/cor_lib_test_main/cocos2d/extensions/GUI/CCScrollView/CCScrollView.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/audio/include/SimpleAudioEngine.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.h"
#include "sub_binding_generated.h"

namespace cor
{
    namespace cocos2dx_mruby_interface
    {

        
          void Cocos2dxBind_bind_func_11(mruby_interface::MrubyState& mrb)
          {
                auto& binder = mrb.ref_binder();
                (void)binder;
                            binder.add_convertable("Cocos2d::EaseExponentialIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseExponentialIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseExponentialIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseExponentialIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseExponentialIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseExponentialOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseExponentialOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseExponentialOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseExponentialOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseExponentialOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseExponentialInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseExponentialInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseExponentialInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseExponentialInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseExponentialInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseSineIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseSineIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseSineIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseSineIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseSineIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseSineOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseSineOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseSineOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseSineOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseSineOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseSineInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseSineInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseSineInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseSineInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseSineInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseElastic", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseElastic", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseElastic", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseElastic", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseElastic", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::EaseElastic");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseElasticIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::EaseElastic");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseElasticOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::EaseElastic");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseElasticInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBounce", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBounce", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBounce", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBounce", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBounce", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::EaseBounce");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBounceIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::EaseBounce");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBounceOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::EaseBounce");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBounceInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBackIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBackIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBackIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBackIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBackIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBackOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBackOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBackOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBackOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBackOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBackInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBackInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBackInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBackInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBackInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseBezierAction", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseBezierAction", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseBezierAction", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseBezierAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseBezierAction", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuadraticActionIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuadraticActionIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuadraticActionIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuadraticActionIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuadraticActionIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuadraticActionOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuadraticActionOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuadraticActionOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuadraticActionOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuadraticActionOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuadraticActionInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuadraticActionInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuadraticActionInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuadraticActionInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuadraticActionInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuarticActionIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuarticActionIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuarticActionIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuarticActionIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuarticActionIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuarticActionOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuarticActionOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuarticActionOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuarticActionOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuarticActionOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuarticActionInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuarticActionInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuarticActionInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuarticActionInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuarticActionInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuinticActionIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuinticActionIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuinticActionIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuinticActionIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuinticActionIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuinticActionOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuinticActionOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuinticActionOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuinticActionOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuinticActionOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseQuinticActionInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseQuinticActionInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseQuinticActionInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseQuinticActionInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseQuinticActionInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCircleActionIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCircleActionIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCircleActionIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCircleActionIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCircleActionIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCircleActionOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCircleActionOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCircleActionOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCircleActionOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCircleActionOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCircleActionInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCircleActionInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCircleActionInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCircleActionInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCircleActionInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCubicActionIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCubicActionIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCubicActionIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCubicActionIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCubicActionIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCubicActionOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCubicActionOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCubicActionOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCubicActionOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCubicActionOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseCubicActionInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseCubicActionInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseCubicActionInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseCubicActionInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseCubicActionInOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionInstant", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ActionInstant", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ActionInstant", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Show", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::Show", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Show", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Show", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Hide", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::Hide", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Hide", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Hide", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ToggleVisibility", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::ToggleVisibility", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ToggleVisibility", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ToggleVisibility", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::RemoveSelf", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::RemoveSelf", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::RemoveSelf", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::RemoveSelf", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FlipX", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::FlipX", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FlipX", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FlipX", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FlipY", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::FlipY", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FlipY", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FlipY", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Place", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::Place", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Place", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Place", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CallFunc", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::CallFunc", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CallFunc", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CallFunc", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CallFuncN", "Cocos2d::CallFunc");
            binder.add_convertable("Cocos2d::CallFuncN", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::CallFuncN", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CallFuncN", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CallFuncN", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::GridAction", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::GridAction", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::GridAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::GridAction", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Grid3DAction", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Grid3DAction", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Grid3DAction", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Grid3DAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Grid3DAction", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::AccelDeccelAmplitude", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::AccelDeccelAmplitude", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::AccelDeccelAmplitude", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::AccelDeccelAmplitude", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::AccelAmplitude", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::AccelAmplitude", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::AccelAmplitude", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::AccelAmplitude", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::DeccelAmplitude", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::DeccelAmplitude", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::DeccelAmplitude", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::DeccelAmplitude", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::StopGrid", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::StopGrid", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::StopGrid", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::StopGrid", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ReuseGrid", "Cocos2d::ActionInstant");
            binder.add_convertable("Cocos2d::ReuseGrid", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ReuseGrid", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ReuseGrid", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Waves3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FlipX3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::FlipX3D");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FlipY3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Lens3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Ripple3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Shaky3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Liquid", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Waves", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Twirl", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionManager", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::Grid3DAction");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::GridAction");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::PageTurn3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ProgressTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ProgressTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ProgressTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ProgressTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ProgressFromTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ProgressFromTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ProgressFromTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ProgressFromTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FadeOutBLTiles", "Cocos2d::FadeOutTRTiles");
            binder.add_convertable("Cocos2d::FadeOutUpTiles", "Cocos2d::FadeOutTRTiles");
            binder.add_convertable("Cocos2d::FadeOutDownTiles", "Cocos2d::FadeOutUpTiles");
            binder.add_convertable("Cocos2d::FadeOutDownTiles", "Cocos2d::FadeOutTRTiles");
            binder.add_convertable("Cocos2d::AtlasNode", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::AtlasNode", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ClippingNode", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::ClippingNode", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::LabelAtlas", "Cocos2d::AtlasNode");
            binder.add_convertable("Cocos2d::LabelAtlas", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::LabelAtlas", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::MotionStreak", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::MotionStreak", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ParticleSystem", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::ParticleSystem", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ParticleSystemQuad", "Cocos2d::ParticleSystem");
            binder.add_convertable("Cocos2d::ParticleSystemQuad", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::ParticleSystemQuad", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ProtectedNode", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::ProtectedNode", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::RenderTexture", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::RenderTexture", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Camera", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::Camera", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::BaseLight", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::BaseLight", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::DirectionLight", "Cocos2d::BaseLight");
            binder.add_convertable("Cocos2d::DirectionLight", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::DirectionLight", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::AmbientLight", "Cocos2d::BaseLight");
            binder.add_convertable("Cocos2d::AmbientLight", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::AmbientLight", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::TextureCache", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShape", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeCircle", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeCircle", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapePolygon", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapePolygon", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeBox", "Cocos2d::PhysicsShapePolygon");
            binder.add_convertable("Cocos2d::PhysicsShapeBox", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeBox", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeSegment", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeSegment", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgePolygon", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgePolygon", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeBox", "Cocos2d::PhysicsShapeEdgePolygon");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeBox", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeBox", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeChain", "Cocos2d::PhysicsShape");
            binder.add_convertable("Cocos2d::PhysicsShapeEdgeChain", "Cocos2d::Ref");

          }

    }
}
