#include "cor_mruby_interface/sources/basic_bind.h"
#include "cor_mruby_interface/sources/mruby_array.h"
#include "cor_mruby_interface/sources/mruby_array_tmpl.h"
#include "cor_mruby_interface/sources/mruby_experimental.h"
#include "cor_mruby_interface/sources/mruby_ref_container.h"
#include "cor_mruby_interface/sources/mruby_state.h"
#include "cor_cocos2dx_converter/sources/cocos2dx_experimental.h"
#include "cor_cocos2dx_converter/sources/collision_2d_node.h"
#include "cor_cocos2dx_converter/sources/easy_http_client.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_cost_grid_space.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_cost_grid_space_e.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_effect.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_group.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_sensor.h"
#include "cor_cocos2dx_converter/sources/rts/rts_object_system.h"
#include "cor_cocos2dx_converter/sources/step_size_scene.h"
#include "cor_cocos2dx_converter/sources/textured_triangle_node.h"
#include "cor_cocos2dx_converter/sources/type_converter.h"
#include "cor_cocos2dx_converter/sources/type_converter_tmpl.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_experimental.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_array.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_mruby_ref.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_value.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.h"
#include "cor_cocos2dx_mruby_interface/sources/mruby_script_engine.h"
#include "cor_cocos2dx_mruby_interface/sources/sprite_experimental.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/cocos2d.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/ui/UIEditBox/UIEditBox.h"
#include "../projects/cor_lib_test_main/cocos2d/extensions/GUI/CCScrollView/CCScrollView.h"
#include "../projects/cor_lib_test_main/cocos2d/cocos/audio/include/SimpleAudioEngine.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos_weak_ptr.h"
#include "cor_cocos2dx_mruby_interface/sources/cocos2dx_bind.h"
#include "sub_binding_generated.h"

namespace cor
{
    namespace cocos2dx_mruby_interface
    {

        
          void Cocos2dxBind_bind_func_10(mruby_interface::MrubyState& mrb)
          {
                auto& binder = mrb.ref_binder();
                (void)binder;
                            binder.add_convertable("Cocos2d::Texture2D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Touch", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Event", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventTouch", "Cocos2d::Event");
            binder.add_convertable("Cocos2d::EventTouch", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Node", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxConverter::Cocos2dxExperimental", "CorMrubyInterface::AnyWP");
            binder.add_convertable("Cocos2d::DrawNode", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::DrawNode", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxConverter::Collision2dNode", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::EasyHttpClient", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectSensor", "CorMrubyInterface::AnyWP");
            binder.add_convertable("Cocos2d::SpriteFrame", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::AnimationFrame", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Animation", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Action", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FiniteTimeAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FiniteTimeAction", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Speed", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Speed", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Follow", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Follow", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionInterval", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ActionInterval", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ActionInterval", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Sequence", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Sequence", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Sequence", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Sequence", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Repeat", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Repeat", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Repeat", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Repeat", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::RepeatForever", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::RepeatForever", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::RepeatForever", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::RepeatForever", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Spawn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Spawn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Spawn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Spawn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::RotateTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::RotateTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::RotateTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::RotateTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::RotateBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::RotateBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::RotateBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::RotateBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::MoveBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::MoveBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::MoveBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::MoveBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::MoveTo", "Cocos2d::MoveBy");
            binder.add_convertable("Cocos2d::MoveTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::MoveTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::MoveTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::MoveTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::SkewTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::SkewTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::SkewTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::SkewTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::SkewBy", "Cocos2d::SkewTo");
            binder.add_convertable("Cocos2d::SkewBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::SkewBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::SkewBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::SkewBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::JumpBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::JumpBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::JumpBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::JumpBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::JumpTo", "Cocos2d::JumpBy");
            binder.add_convertable("Cocos2d::JumpTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::JumpTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::JumpTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::JumpTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::BezierBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::BezierBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::BezierBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::BezierBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::BezierTo", "Cocos2d::BezierBy");
            binder.add_convertable("Cocos2d::BezierTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::BezierTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::BezierTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::BezierTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ScaleTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ScaleTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ScaleTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ScaleTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ScaleBy", "Cocos2d::ScaleTo");
            binder.add_convertable("Cocos2d::ScaleBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ScaleBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ScaleBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ScaleBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Blink", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Blink", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Blink", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Blink", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FadeTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::FadeTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FadeTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FadeTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FadeIn", "Cocos2d::FadeTo");
            binder.add_convertable("Cocos2d::FadeIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::FadeIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FadeIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FadeIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FadeOut", "Cocos2d::FadeTo");
            binder.add_convertable("Cocos2d::FadeOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::FadeOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::FadeOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::FadeOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::TintTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::TintTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::TintTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::TintTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::TintBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::TintBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::TintBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::TintBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::DelayTime", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::DelayTime", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::DelayTime", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::DelayTime", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ReverseTime", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ReverseTime", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ReverseTime", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ReverseTime", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Animate", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Animate", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Animate", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Animate", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::TargetedAction", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::TargetedAction", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::TargetedAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::TargetedAction", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectAction", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::RtsObject", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectGroup", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectCostGridSpace", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectCostGridSpaceExperimental", "CorMrubyInterface::AnyWP");
            binder.add_convertable("CorCocos2dxConverter::TexturedTriangleNode", "Cocos2d::Node");
            binder.add_convertable("CorCocos2dxConverter::TexturedTriangleNode", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectEffect", "CorMrubyInterface::AnyWP");
            binder.add_convertable("Cocos2d::Image", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Sprite", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::Sprite", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::FontAtlas", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Label", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::Label", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Layer", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::Layer", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::LayerColor", "Cocos2d::Layer");
            binder.add_convertable("Cocos2d::LayerColor", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::LayerColor", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventListener", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventListenerTouchOneByOne", "Cocos2d::EventListener");
            binder.add_convertable("Cocos2d::EventListenerTouchOneByOne", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventListenerTouchAllAtOnce", "Cocos2d::EventListener");
            binder.add_convertable("Cocos2d::EventListenerTouchAllAtOnce", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionTween", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ActionTween", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ActionTween", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ActionTween", "Cocos2d::Ref");
            binder.add_convertable("Cocos2dExtension::ScrollView", "Cocos2d::Layer");
            binder.add_convertable("Cocos2dExtension::ScrollView", "Cocos2d::Node");
            binder.add_convertable("Cocos2dExtension::ScrollView", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxConverter::RtsObjectSystem", "CorMrubyInterface::AnyWP");
            binder.add_convertable("Cocos2d::Scene", "Cocos2d::Node");
            binder.add_convertable("Cocos2d::Scene", "Cocos2d::Ref");
            binder.add_convertable("CorCocos2dxMrubyInterface::CocosMrubyRef", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Director", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Animation3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::Animate3D", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::Animate3D", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::Animate3D", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::Animate3D", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventCustom", "Cocos2d::Event");
            binder.add_convertable("Cocos2d::EventCustom", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventDispatcher", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventListenerCustom", "Cocos2d::EventListener");
            binder.add_convertable("Cocos2d::EventListenerCustom", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EventListenerKeyboard", "Cocos2d::EventListener");
            binder.add_convertable("Cocos2d::EventListenerKeyboard", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionCamera", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ActionCamera", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ActionCamera", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ActionCamera", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::OrbitCamera", "Cocos2d::ActionCamera");
            binder.add_convertable("Cocos2d::OrbitCamera", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::OrbitCamera", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::OrbitCamera", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::OrbitCamera", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::PointArray", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CardinalSplineTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::CardinalSplineTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CardinalSplineTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CardinalSplineTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CardinalSplineBy", "Cocos2d::CardinalSplineTo");
            binder.add_convertable("Cocos2d::CardinalSplineBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::CardinalSplineBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CardinalSplineBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CardinalSplineBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CatmullRomTo", "Cocos2d::CardinalSplineTo");
            binder.add_convertable("Cocos2d::CatmullRomTo", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::CatmullRomTo", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CatmullRomTo", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CatmullRomTo", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::CardinalSplineBy");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::CardinalSplineTo");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::CatmullRomBy", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::ActionEase", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::ActionEase", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::ActionEase", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::ActionEase", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseRateAction", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseRateAction", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseRateAction", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseRateAction", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseRateAction", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::EaseRateAction");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseIn", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::EaseRateAction");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseOut", "Cocos2d::Ref");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::EaseRateAction");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::ActionEase");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::ActionInterval");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::FiniteTimeAction");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::Action");
            binder.add_convertable("Cocos2d::EaseInOut", "Cocos2d::Ref");

          }

    }
}
